# Site settings
title: M Clarisse Valera
email: clarisse.valera@cal.berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Clarisse Valera's portfolio website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mcvalera.github.io/" # the base hostname & protocol for your site
twitter_username: claaang
github_username:  mcvalera

# Build settings
markdown: kramdown
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      category: blog
      author: Clarisse
